language: php

php:
  - 5.4

before_script:
    - composer require --dev "codeception/codeception:1.6.7"
    - php -S localhost:31415 -t www/ &

script: sh test.sh

env:
    - PHUNDAMENT_TEST=true

branches:
  only:
    - master
    - develop
