language: php

php:
  - 5.4

before_script:
    - composer install --prefer-dist
    - composer require --dev --prefer-dist "codeception/codeception:1.6.2"
    - app/yiic migrate --interactive=0
    - php -S localhost:31415 -t www/ &

script: sh test.sh

env:
    - PHUNDAMENT_TEST=true

branches:
  only:
    - master
